version: '3.4'
services:
    transpiler:
        build:
            context: .
            target: dev
        volumes: &app
            - .:/usr/src/app/
        command: yarn build:watch --preserveWatchOutput
    server:
        build:
            context: .
            target: dev
        depends_on:
            - transpiler
        volumes: *app
        ports:
            - '4000:4000'
        command: yarn start
