version: '3.4'
services:
    transpiler:
        build:
            context: .
            target: dev
        volumes:
            - .:/usr/src/app/
        command: yarn build:watch
    server:
        build:
            context: .
            target: dev
        depends_on:
            - transpiler
        volumes:
            - .:/usr/src/app/
        ports:
            - '4000:4000'
        command: yarn start
